spring:
  datasource:
    url: jdbc:h2:mem:maindb

  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    hibernate:
      ddl-auto: none

  sql:
    init:
      mode: always
      data-locations: data.sql
      schema-locations: schema.sql
