spring:
  datasource:
    url: jdbc:h2:mem:maindb

  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    hibernate:
      ddl-auto: none

  sql:
    init:
      mode: always
      data-locations: classpath:data.sql
      schema-locations: classpath:schema.sql

  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    cache: false
    mode: HTML

    web:
      resources:
        static-locations: classpath:/static/

    h2:
      console:
        enabled: true
        path: /h2-console

  server:
    port: 8080